name: Node.js CI

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node-version: [18.x] # uWebSockets has blacklisted 16.x
    services:
      postgresql:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        volumes:
          - /dependencies/postgresql/entrypoint:/docker-entrypoint-initdb.d
      postgrest:
        image: postgrest/postgrest:latest
        ports:
          - 5433:5433
        env:
          PGRST_DB_ANON_ROLE: "anon"
          PGRST_DB_SCHEMAS: "public, private"
          PGRST_DB_EXTRA_SEARCH_PATH: "public"
          PGRST_DB_URI: postgresql://postgres:postgres@localhost:5432/postgres
          PGRST_SERVER_PORT: "5433"
          PGRST_JWT_SECRET: "4JLbS4XURTDIxQI6/2Rdw5pEkDuRxwjRZ6h0hsRxuIk="
          PGRST_JWT_SECRET_IS_BASE64: "true"
          PGRST_JWT_AUD: "crestfall"
          PGRST_LOG_LEVEL: "warn"
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:

    - name: pwd
      run: pwd

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        cache: 'npm'
        node-version: ${{ matrix.node-version }}

    - name: Create .env file
      run: bash ./env.test.sh

    - name: Install dependencies
      run: npm install

    - name: Run test
      run: node ./index.test.mjs