name: Node.js CI

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 2
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]
    steps:

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        cache: 'npm'
        node-version: ${{ matrix.node-version }}

    - name: pwd
      run: pwd

    - name: ls
      run: ls

    - name: docker --version
      run: docker --version

    - name: Create .env file
      run: bash ./env.test.sh

    - name: Install dependencies
      run: npm install

    - name: Run test
      run: node ./index.test.mjs